<!DOCTYPE html>
<html>
     <head>
	    <!-- Required meta tags -->
		<meta charset="<?= DEFAULT_CHARSET ?>">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

	     <!-- Flexbox grid -->
		 <link rel="stylesheet" href="<?= TEMPLATES_DIR_URL . 'Zqpalnik/front/css/flexboxgrid.min.css' ?>">
		 <!-- Font awesome -->
		 <link rel="stylesheet" href="<?= TEMPLATES_DIR_URL . 'Zqpalnik/front/css/fontawesome/css/all.min.css' ?>">
    	 <!-- My customizations CSS -->
		<link rel="stylesheet" href="<?= TEMPLATES_DIR_URL . 'Zqpalnik/front/css/customiz.css' ?>">
		
	     <title><?= \core\Template::getTitle(); ?></title>
	 </head>
	 <body>
	        <div>
                <header>
					     <div class="row">
						     <!-- Logo column -->
						     <div class="col-xs-3  col-sm-2">
							     <div class="box">
								    <p class='site-logo'><?= strtoupper(SITE_NAME); ?></p>
								 </div>
							 </div>
						     <div class="col-xs-9 col-sm-10">
							     <div class="box">
									 <!-- Main nav-->
								     <nav id="main_nav" class="horizontal-nav horizontal-nav-bar-btns">
									    <ul>
										   <li><a href="#" class="btn"><i class="fa fa-home"></i> <span class='hnav-bar-btn-txt hover-label'>Home</span></a></li>
										   <li><a href="#" class="btn" onclick="$('ul.horizontal-nav-dropdown').toggle();"><i class="fa fa-film"></i> <span class='hnav-bar-btn-txt hover-label'>Videos</span> <i class="fa fa-angle-down"></i></a>
										           <ul class="horizontal-nav-dropdown" onmouseleave="$('ul.horizontal-nav-dropdown').hide();">
												        <li class="horizontal-nav-dropdown-section"><a href="#" onclick="$('.hnd-section-movies-elem').toggle();">Movies <i class="fa fa-angle-down"></i></a></li>
														    <li class="hnd-section-movies-elem"><a href="#">Comedy</a></li>
															<li class="hnd-section-movies-elem"><a href="#">Drama</a></li>
															<li class="hnd-section-movies-elem"><a href="#">Horror</a></li>
															<li class="hnd-section-movies-elem"><a href="#">Sci-fi</a></li>
															<li class="hnd-section-movies-elem"><a href="#">Anime</a></li>
															<li class="hnd-section-movies-elem"><a href="#">Documental</a></li>
															<li class="hnd-section-movies-elem"><a href="#">etc.</a></li>
														<li class="horizontal-nav-dropdown-section"><a href="#" onclick="$('.hnd-section-tvseries-elem').toggle();">TV Series <i class="fa fa-angle-down"></i></a></li>
														    <li class="hnd-section-tvseries-elem"><a href="#">Comedy</a></li>
															<li class="hnd-section-tvseries-elem"><a href="#">Drama</a></li>
															<li class="hnd-section-tvseries-elem"><a href="#">Horror</a></li>
															<li class="hnd-section-tvseries-elem"><a href="#">Sci-fi</a></li>
															<li class="hnd-section-tvseries-elem"><a href="#">Anime</a></li>
															<li class="hnd-section-tvseries-elem"><a href="#">Documental</a></li>
															<li class="hnd-section-tvseries-elem"><a href="#">etc.</a></li>
														<li class="horizontal-nav-dropdown-section"><a href="#" onclick="$('.hnd-section-musical-elem').toggle();">Musical <i class="fa fa-angle-down"></i></a></li>
														    <li class="hnd-section-musical-elem"><a href="#">Heavy Metal</a></li>
															<li class="hnd-section-musical-elem"><a href="#">Rock</a></li>
															<li class="hnd-section-musical-elem"><a href="#">Hip-hop</a></li>
															<li class="hnd-section-musical-elem"><a href="#">Pop</a></li>
															<li class="hnd-section-musical-elem"><a href="#">House</a></li>
															<li class="hnd-section-musical-elem"><a href="#">etc.</a></li>
														<li class="horizontal-nav-dropdown-section"><a href="#">Funny</a></li>
														<li class="horizontal-nav-dropdown-section"><a href="#">Educational</a></li>
														<li class="horizontal-nav-dropdown-section"><a href="#">News</a></li>
														<li class="horizontal-nav-dropdown-section"><a href="#">Others</a></li>																												
												   </ul>
										   </li>
										   <li><a href="#" class="btn"><i class="fa fa-broadcast-tower "></i> <span class='hnav-bar-btn-txt hover-label'>Channels</span></a></li>
										   <li><a href="#" class="btn"><i class="fa fa-list-ul "></i> <span class='hnav-bar-btn-txt hover-label'>Playlists</span></a></li>
										   <li><a href="#" class="btn"><i class="fa fa-users"></i> <span class='hnav-bar-btn-txt hover-label'>Users</span></a></li>
										   <li class="show-on-mobile"><a href="#"  class="btn" onclick="$('#right_sidebar').hide();  $('#main_nav').toggle(); $('#main_search').toggle();"><i class="fa fa-search"></i> <span class='hnav-bar-btn-txt hover-label'>Search</span></a></li>
										   <li class="show-on-mobile hide-on-bigger-dev"><a href="#"  class="btn" onclick="$('#right_sidebar').toggle();"><i class="fa fa-angle-left"></i><i class="fa fa-bars"></i> <span class='hnav-bar-btn-txt hover-label'>Expand sidebar</span></a></li>
										   <li>&nbsp;&nbsp;<a href="#" class="btn"><i class="fa fa-sign-in-alt "></i> <span class='hnav-bar-btn-txt hover-label'>Log in</span></a> or <a href="#" class="btn"><i class="fa fa-user-plus "></i> <span class='hnav-bar-btn-txt hover-label'>Sign up</span></a></li>
										</ul>
									 </nav>								
                                   
								     <!-- The main search form -->
								    <form id="main_search" class="search-form">
									    <input type="text" name="searchfor" placeholder="Search for...">
										<select name="search-type">
										   <option value="all">Everything</option>
										   <option value="users">Users</option>
										   <option value="videos">Videos</option>
										   <option value="channels">Channels</option>
										   <option value="playlists">Playlists</option>
										</select>
										<button type="submit" name="search-submit"><i class="fa fa-search"></i></button>
										&nbsp;&nbsp;
										<button type="button" class="close hover-label-wrapper search-hide-btn" onclick="$('#main_nav').toggle(); $('#main_search').toggle();"><i class='fa fa-times'></i><span class="hnav-bar-btn-txt hover-label">Hide the search form</span></button>
									</form>
								 </div>
							 </div>
                        </div>							 
					</header>
					<aside id="right_sidebar" onmouseleave="$(this).hide();">
						 <!-- Mobile nav -->
						 <nav id="mobile_nav">
							 <ul>
							     <li><a href="#" class="btn"><i class="fa fa-home"></i> Home</a></li>
								 <li onmouseleave="$('.mob-nav-sub-videos').hide();"><a href="#" class="btn" onclick="$('.mob-nav-sub-videos').toggle();"><i class="fa fa-film"></i> Videos <i class="fa fa-angle-down"></i></a>
								        <ul class="mob-nav-sub-videos">
	                                        <li onmouseleave="$('.mob-nav-sub-movies').hide();"><a href="#" class="btn" onclick="$('.mob-nav-sub-movies').toggle();">Movies <i class="fa fa-angle-down"></i></a>
											     <ul class="mob-nav-sub-movies">
												     <li><a href="#" class="btn">Comedy</a></li>
												     <li><a href="#" class="btn">Drama</a></li>
												     <li><a href="#" class="btn">Horror</a></li>
												     <li><a href="#" class="btn">Sci-fi</a></li>
												     <li><a href="#" class="btn">Anime</a></li>
												     <li><a href="#" class="btn">Documental</a></li>
												     <li><a href="#" class="btn">etc.</a></li>
												 </ul>
											</li>
										    <li onmouseleave="$('.mob-nav-sub-tvseries').hide();"><a href="#" class="btn" onclick="$('.mob-nav-sub-tvseries').toggle();">TV Series <i class="fa fa-angle-down"></i></a>
											     <ul class="mob-nav-sub-tvseries">
												     <li><a href="#" class="btn">Comedy</a></li>
												     <li><a href="#" class="btn">Drama</a></li>
												     <li><a href="#" class="btn">Horror</a></li>
												     <li><a href="#" class="btn">Sci-fi</a></li>
												     <li><a href="#" class="btn">Anime</a></li>
												     <li><a href="#" class="btn">Documental</a></li>
												     <li><a href="#" class="btn">etc.</a></li>
												 </ul>											
											</li>
										    <li onmouseleave="$('.mob-nav-sub-musical').hide();"><a href="#" class="btn" onclick="$('.mob-nav-sub-musical').toggle();">Musical <i class="fa fa-angle-down"></i></a>
											     <ul class="mob-nav-sub-musical">
												     <li><a href="#" class="btn">Heavy Metal</a></li>
												     <li><a href="#" class="btn">Rock</a></li>
												     <li><a href="#" class="btn">Hip-hop</a></li>
												     <li><a href="#" class="btn">Pop</a></li>
												     <li><a href="#" class="btn">House</a></li>
												     <li><a href="#" class="btn">etc.</a></li>
												 </ul>											
											</li>
											<li><a href="#" class="btn">Funny</a></li>
											<li><a href="#" class="btn">Educational</a></li>
											<li><a href="#" class="btn">News</a></li>
											<li><a href="#" class="btn">Others</a></li>
										</ul>
								 </li>
								 <li><a href="#" class="btn"><i class="fa fa-broadcast-tower"></i> Channels</a></li>
								 <li><a href="#" class="btn"><i class="fa fa-list-ul"></i> Playlists</a></li>
							     <li><a href="#" class="btn"><i class="fa fa-users"></i> Users</a></li>
							 </ul>
						 </nav>
					</aside>
					